name:  Debug Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build solution
      run: dotnet build --configuration Release
      env:
        Configuration: Debug
        RuntimeIdentifier: win-${{ matrix.targetplatform }}
