name: Build Smoke Test

on:
  push:
    branches:
    - main 
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build solution
      run: dotnet build
      working-directory: ./Swapper
      env:
        Configuration: Release

    # these do not actually publish anything; they are just ensuring the publish
    # profiles are working
    - name: Publish (x64)
      run: dotnet publish
      working-directory: ./Swapper
      env:
        Configuration: Release
        PublishProfile: folder-x64
    - name: Publish (x86)
      run: dotnet publish
      working-directory: ./Swapper
      env:
        Configuration: Release
        PublishProfile: folder-x86
